-- MySQL Workbench Synchronization
-- Generated: 2020-03-28 17:39
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: glei-

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `finance` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `finance`.`cadastro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `sobreNome` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` CHAR(2) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cadastrocol_UNIQUE` (`sobreNome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `finance`.`credito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `finance`.`debito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `status` ENUM('PAGO', 'PENDENTE', 'AGENDADO') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `finance`.`cicloPagamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mes` VARCHAR(45) NULL DEFAULT NULL,
  `ano` VARCHAR(45) NULL DEFAULT NULL,
  `credito_id` INT(11) NOT NULL,
  `debito_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `credito_id`, `debito_id`),
  INDEX `fk_cicloPagamento_credito_idx` (`credito_id` ASC) VISIBLE,
  INDEX `fk_cicloPagamento_debito1_idx` (`debito_id` ASC) VISIBLE,
  CONSTRAINT `fk_cicloPagamento_credito`
    FOREIGN KEY (`credito_id`)
    REFERENCES `finance`.`credito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cicloPagamento_debito1`
    FOREIGN KEY (`debito_id`)
    REFERENCES `finance`.`debito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
